first_name = input("What is your given name?")
family_name = input("What is your family name?")
street_address = input("What is your street address?")
city_postal = input("What is your city and postal code?")
print(first_name + " " + family_name)
print(street_address)
print(city_postal)